behaviors:
  HighwayAI:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 40960
      learning_rate: 0.0001
      beta: 0.0001
      epsilon: 0.1
      lambd: 0.9
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
      memory: null
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    init_path: null
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 5000000
    time_horizon: 512
    summary_freq: 10000
    threaded: true
    self_play: null
    behavioral_cloning: null
env_settings:
  env_path: builds/DRL-highway
  env_args: null
  base_port: 5005
  num_envs: 4
  seed: -1
engine_settings:
  width: 400
  height: 400
  quality_level: 5
  time_scale: 100.0
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false
environment_parameters: null
checkpoint_settings:
  run_id: Highway_29
  initialize_from: null
  load_model: false
  resume: false
  force: false
  train_model: false
  inference: false
debug: false
